name: New subscription request
description: Request a new Azure Subscription.
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this form. Please provide the below details for your new subscription.