name: 🏠 Subscription
description: Request a new Azure Subscription
title: "<Project name>"
body:
- type: input
  id: displayName
  attributes:
    label: Subscription display name
    description: "What will be the display name of the subscription?"
    placeholder: "ex. sub-nexus-project-prod"
  validations:
    required: true
- type: dropdown
  id: virtualNetworkEnabled
  attributes:
    label: Deploy a virtual network?
    description: "Option to deploy a virtual network into the new subscription."
    options:
      - "No"
      - "Yes"
    default: 0
  validations:
    required: true
- type: textarea
  id: virtualNetworkAddressSpace
  attributes:
    label: Virtual network address spaces
    description: "The address spaces for the virtual network to be created."
    placeholder: "ex. 10.0.0.0/16"
  validations:
    required: false
- type: dropdown
  id: virtualNetworkPeeringEnabled
  attributes:
    label: Enable virtual network peering
    description: "Option to peer the new virtual network with the platform's hub network."
    options:
      - "No"
      - "Yes"
    default: 0
  validations:
    required: false
- type: textarea
  id: hubNetworkResourceId
  attributes:
    label: Hub network resource Id
    description: "The resource ID of the Virtual Network or Virtual WAN Hub in the hub to which the created Virtual Network."
    placeholder: "ex. /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/rsg-uks-net-vwan-001/providers/Microsoft.Network/virtualHubs/vhub-uks-001"
  validations:
    required: false
