name: Subscription
description: Request new subscription
body:
  - type: markdown
    attributes:
      value: |
        Before opening a bug report, please search for the behaviour in the existing issues.
        ---
        Thank you for taking the time to file a bug report. To address this bug as fast as possible, we need some information.
