name: Subscription
description: Request new subscription
body:
  - type: input
    id: os
    attributes:
      label: Operating system
      description: "Which operating system do you use? Please provide the version as well."
      placeholder: "macOS Big Sur 11.5.2"
    validations:
      required: true
