name: Deploy to Azure
on:
  issues:
    types: [closed]
permissions:
  id-token: write
  contents: read
jobs:
  ParseSubscriptionProperties:
    runs-on: ubuntu-latest
    steps:
      - uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/newSub.yml

      - run: cat ${HOME}/issue-parser-result.json

      - run: echo "Fetching subscription properties."
        env:
          displayName: ${{ steps.issue-parser.outputs.issueparser_subscription_display_name }}
          virtualNetworkEnabled: ${{ steps.issue-parser.outputs.issueparser_deploy_a_virtual_network }}
          virtualNetworkAddressSpace: ${{ steps.issue-parser.outputs.issueparser_virtual_network_address_spaces }}
          virtualNetworkPeeringEnabled: ${{ steps.issue-parser.outputs.issueparser_enable_virtual_network_peering }}
          hubNetworkResourceId: ${{ steps.issue-parser.outputs.issueparser_hub_network_resource_id }}
          workloadAdminGroup: ${{ steps.issue-parser.outputs.issueparser_workload_admin_group }}
    outputs:
            displayName: ${{ steps.issue-parser.outputs.issueparser_subscription_display_name }}
            virtualNetworkEnabled: ${{ steps.issue-parser.outputs.issueparser_deploy_a_virtual_network }}
            virtualNetworkAddressSpace: ${{ steps.issue-parser.outputs.issueparser_virtual_network_address_spaces }}
            virtualNetworkPeeringEnabled: ${{ steps.issue-parser.outputs.issueparser_enable_virtual_network_peering }}
            hubNetworkResourceId: ${{ steps.issue-parser.outputs.issueparser_hub_network_resource_id }}
            workloadAdminGroup: ${{ steps.issue-parser.outputs.issueparser_workload_admin_group }}

  DeployToAzure:
    runs-on: ubuntu-latest
    needs: ParseSubscriptionProperties
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Az CLI login"
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: "Provision subscription"
        env:
          displayName: ${{ needs.ParseSubscriptionProperties.outputs.displayName }}
          virtualNetworkEnabled: ${{ needs.ParseSubscriptionProperties.outputs.virtualNetworkEnabled }}
          virtualNetworkAddressSpace: ${{ needs.ParseSubscriptionProperties.outputs.virtualNetworkAddressSpace }}
          virtualNetworkPeeringEnabled: ${{ needs.ParseSubscriptionProperties.outputs.virtualNetworkPeeringEnabled }}
          hubNetworkResourceId: ${{ needs.ParseSubscriptionProperties.outputs.hubNetworkResourceId }}
          workloadAdminGroup: ${{ needs.ParseSubscriptionProperties.outputs.workloadAdminGroup }}
        run: |
          az deployment mg create -f ./modules/sub-vending.bicep -p displayName=${displayName} virtualNetworkEnabled=${virtualNetworkEnabled} virtualNetworkAddressSpace=${virtualNetworkAddressSpace} virtualNetworkPeeringEnabled=${virtualNetworkPeeringEnabled} hubNetworkResourceId=${hubNetworkResourceId} -l swedencentral -m alz-corp
