name: Issue Forms Body Parser
on: issues
jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/newSub.yml # optional but recommended

      - run: cat ${HOME}/issue-parser-result.json

      - run: echo $subscription_display_name
        env:
          displayName: ${{ steps.issue-parser.outputs.issueparser_subscription_display_name }}

